colors:
 primary:
   background: '#242424'
   foreground: '#f6f3e8'
 normal:
   black:   '#666666'

key_bindings:
  - { key: Space, mods: Control, chars: "\x00" }
  - { key: Left,  mods: Control, chars: "\x1bb" }
  - { key: Right, mods: Control, chars: "\x1bf" }
  - { key: Key1,  mods: Control, chars: "\x1b1" }
  - { key: Key2,  mods: Control, chars: "\x1b2" }
  - { key: Key3,  mods: Control, chars: "\x1b3" }
  - { key: Key4,  mods: Control, chars: "\x1b4" }
  - { key: Key5,  mods: Control, chars: "\x1b5" }
  - { key: Key6,  mods: Control, chars: "\x1b6" }
  - { key: Key7,  mods: Control, chars: "\x1b7" }
  - { key: Key8,  mods: Control, chars: "\x1b8" }
  - { key: Key9,  mods: Control, chars: "\x1b9" }
  - { key: Key0,  mods: Control, chars: "\x1b0" }
  - { key: A,     mods: Alt,     chars: "\x1ba" }
  - { key: B,     mods: Alt,     chars: "\x1bb" }
  - { key: C,     mods: Alt,     chars: "\x1bc" }
  - { key: D,     mods: Alt,     chars: "\x1bd" }
  - { key: E,     mods: Alt,     chars: "\x1be" }
  - { key: F,     mods: Alt,     chars: "\x1bf" }
  - { key: G,     mods: Alt,     chars: "\x1bg" }
  - { key: H,     mods: Alt,     chars: "\x1bh" }
  - { key: I,     mods: Alt,     chars: "\x1bi" }
  - { key: J,     mods: Alt,     chars: "\x1bj" }
  - { key: K,     mods: Alt,     chars: "\x1bk" }
  - { key: L,     mods: Alt,     chars: "\x1bl" }
  - { key: M,     mods: Alt,     chars: "\x1bm" }
  - { key: N,     mods: Alt,     chars: "\x1bn" }
  - { key: O,     mods: Alt,     chars: "\x1bo" }
  - { key: P,     mods: Alt,     chars: "\x1bp" }
  - { key: Q,     mods: Alt,     chars: "\x1bq" }
  - { key: R,     mods: Alt,     chars: "\x1br" }
  - { key: S,     mods: Alt,     chars: "\x1bs" }
  - { key: T,     mods: Alt,     chars: "\x1bt" }
  - { key: U,     mods: Alt,     chars: "\x1bu" }
  - { key: V,     mods: Alt,     chars: "\x1bv" }
  - { key: W,     mods: Alt,     chars: "\x1bw" }
  - { key: X,     mods: Alt,     chars: "\x1bx" }
  - { key: Y,     mods: Alt,     chars: "\x1by" }
  - { key: Z,     mods: Alt,     chars: "\x1bz" }
