;;; flymake-jshint-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flymake-jshint.el

(autoload 'flymake-jshint-load "flymake-jshint" "\
Configure flymake mode to check the current buffer's JavaScript syntax." t)
(register-definition-prefixes "flymake-jshint" '("flymake-jshint-" "jshint-configuration-path"))

;;; End of scraped data

(provide 'flymake-jshint-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flymake-jshint-autoloads.el ends here
