#!/bin/bash
set -e
CURR=0
grep -qm1 'level:.*auto' /proc/acpi/ibm/fan && CURR=1

function chirp() {
	echo "Detected: [$1] trigger, setting to full-speed"
}



TEMP=$(sensors coretemp-isa-0000 -j | grep -m1 temp1_input | /usr/bin/grep -oE '[0-9]+\.[0-9]{2}*')
# echo "DEBUG: $CURR $TEMP"
if [[ "`echo "$TEMP > 62" | bc -l`" == 1 ]]
then
	[[ $CURR -eq 0 ]] && exit 0
	chirp temp
	echo 'level full-speed' > /proc/acpi/ibm/fan
	exit 0
fi

CPU_UTIL=$(top -b -n 1 | grep -m1 Cpu | awk '{print $2}')
if [[ "`echo "$CPU_UTIL > 85" | bc -l`" == 1 ]]
then
	[[ $CURR -eq 0 ]] && exit 0
	chirp util
	echo 'level full-speed' > /proc/acpi/ibm/fan
else
	echo 'level auto' > /proc/acpi/ibm/fan
fi
