#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.

PATH=${HOME}/bin/flatpak/:${HOME}/bin/:${PATH}
OLDHOME=/mnt/myth/bak/cosmo/cosmo/home/current/home/iphands
OLDROOT=/mnt/myth/bak/cosmo/cosmo/rootfs/current/rootfs

# Change your keymap:
xmodmap "/home/iphands/.Xmodmap"
# google-chrome-unstable &
# conky -c ~/.conky/conkyrc &
feh --bg-center ~/Documents/tux.png
xosview &
nm-applet &
blueman-applet &
/home/iphands/prog/rust_tray/target/release/rust_tray --auto &
xinput disable `xinput list | grep ELAN901C | grep -Eo 'id=[0-9]+' | cut -d= -f2`

# And last but not least we start fluxbox.
# Because it is the last app you have to run it with ''exec'' before it.

# exec fluxbox
# or if you want to keep a log:
exec fluxbox -log "/home/iphands/.fluxbox/log"
