;;; flycheck-pyre-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flycheck-pyre.el

(autoload 'flycheck-pyre-setup "flycheck-pyre" "\
Setup Flycheck Pyre." t)
(register-definition-prefixes "flycheck-pyre" '("flycheck-pyre-"))

;;; End of scraped data

(provide 'flycheck-pyre-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flycheck-pyre-autoloads.el ends here
